### ISSUE TITLE
Missing Package

### ISSUE THREAD

**Issue by rdhillbb** [Clement-Jean/proto-go-course#2]
I purchase your protobuf class. I get the following error during make

go: finding module for package google.golang.org/protobuf/runtime/protoimpl
go: finding module for package github.com/Clement-Jean/proto-go-course/proto
go: finding module for package google.golang.org/protobuf/encoding/protojson
go: finding module for package google.golang.org/protobuf/proto
go: finding module for package google.golang.org/protobuf/reflect/protoreflect
go: found google.golang.org/protobuf/encoding/protojson in google.golang.org/protobuf v1.28.1
go: found google.golang.org/protobuf/proto in google.golang.org/protobuf v1.28.1
go: found google.golang.org/protobuf/reflect/protoreflect in google.golang.org/protobuf v1.28.1
go: found google.golang.org/protobuf/runtime/protoimpl in google.golang.org/protobuf v1.28.1
go: finding module for package github.com/Clement-Jean/proto-go-course/proto
proto-go-course imports
	github.com/Clement-Jean/proto-go-course/proto: module github.com/Clement-Jean/proto-go-course@latest found (v0.0.0-20230110031943-4aa6089b4837), but does not contain package github.com/Clement-Jean/proto-go-course/proto

**Comment by Clement-Jean** [comment]
This is happening if you didn't generate the go code for protobuf. So you can do a `make generate` first and then you `go mod tidy` or `go run`. Hope that helps. Let me know.
